services:
  db:
    image: postgres:16.2
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    container_name: cutabove-db

  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    container_name: cutabove-redis
